### ISSUE TITLE
push. each 时解析 数组元素时异常

### ISSUE THREAD

**Issue by GitHubLhp123** [whaleal/mars#26]
Document{{$push=Document{{logList={"$each":{}}}}}}

org.bson.codecs.configuration.CodecConfigurationException: Unable to get value for property 'key' in Each

	at com.whaleal.mars.codecs.pojo.PropertyAccessorImpl.getError(PropertyAccessorImpl.java:85)
	at com.whaleal.mars.codecs.pojo.PropertyAccessorImpl.get(PropertyAccessorImpl.java:61)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.encodeProperty(EntityEncoder.java:121)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.lambda$encodeEntity$0(EntityEncoder.java:83)
	at com.whaleal.mars.core.aggregation.codecs.ExpressionHelper.document(ExpressionHelper.java:61)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.encodeEntity(EntityEncoder.java:68)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.encode(EntityEncoder.java:56)
	at com.whaleal.mars.codecs.pojo.MarsCodec.encode(MarsCodec.java:128)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.encodeEntity(EntityEncoder.java:89)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.encode(EntityEncoder.java:56)
	at com.whaleal.mars.codecs.pojo.MarsCodec.encode(MarsCodec.java:128)
	at com.whaleal.mars.codecs.pojo.CollectionCodec.encode(CollectionCodec.java:67)
	at com.whaleal.mars.codecs.pojo.CollectionCodec.encode(CollectionCodec.java:47)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.encodeValue(EntityEncoder.java:133)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.encodeProperty(EntityEncoder.java:122)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.lambda$encodeEntity$0(EntityEncoder.java:83)
	at com.whaleal.mars.core.aggregation.codecs.ExpressionHelper.document(ExpressionHelper.java:61)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.encodeEntity(EntityEncoder.java:68)
	at com.whaleal.mars.codecs.pojo.EntityEncoder.encode(EntityEncoder.java:56)
	at com.whaleal.mars.codecs.pojo.MarsCodec.encode(MarsCodec.java:128)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:203)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:217)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:200)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:217)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:159)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:46)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:221)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:187)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77)
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
	at com.mongodb.internal.connection.BsonWriterHelper.writePayloadArray(BsonWriterHelper.java:50)
	at com.mongodb.internal.connection.SplittablePayloadBsonWriter.writeEndDocument(SplittablePayloadBsonWriter.java:64)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:121)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:42)
	at com.mongodb.internal.connection.CommandMessage.addDocumentWithPayload(CommandMessage.java:198)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:182)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:268)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:100)

**Comment by HbnKing** [comment]
fix at 0.7.3

**Comment by HbnKing** [comment]
fix  at 0.7.4
