### ISSUE TITLE
使用update的addToSet时栈溢出

### ISSUE THREAD

**Issue by WhaleFalls0807** [whaleal/mars#27]
java.lang.StackOverflowError
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:68)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:56)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:45)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:19)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:68)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:56)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:45)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:19)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:68)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:56)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:45)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:19)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:68)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:56)
	at com.whaleal.icefrog.core.collection.ArrayIter.<init>(ArrayIter.java:45)

**Comment by HbnKing** [comment]
暂未发现该异常
