### ISSUE TITLE
Unable to get value for property  xxxx

### ISSUE THREAD

**Issue by HbnKing** [whaleal/mars#73]
```
Unable to get value for property 'mongoMemberInfoList' in MongoClusterInformation
org.bson.codecs.configuration.CodecConfigurationException: Unable to get value for property 'mongoMemberInfoList' in MongoClusterInformation
 at com.whaleal.mars.codecs.pojo.PropertyAccessorImpl.getError(PropertyAccessorImpl.java:85)
 at com.whaleal.mars.codecs.pojo.PropertyAccessorImpl.get(PropertyAccessorImpl.java:61)
 at com.whaleal.mars.codecs.pojo.EntityEncoder.encodeProperty(EntityEncoder.java:121)
 at com.whaleal.mars.codecs.pojo.EntityEncoder.lambda$encodeEntity$0(EntityEncoder.java:83)
 at com.whaleal.mars.core.aggregation.codecs.ExpressionHelper.document(ExpressionHelper.java:50)
 at com.whaleal.mars.codecs.pojo.EntityEncoder.encodeEntity(EntityEncoder.java:68)
 at com.whaleal.mars.codecs.pojo.EntityEncoder.encode(EntityEncoder.java:56)
 at com.whaleal.mars.codecs.pojo.MarsCodec.encode(MarsCodec.java:128)
 at com.whaleal.mars.session.DatastoreImpl.toDocument(DatastoreImpl.java:774)
 at com.whaleal.mars.session.DatastoreImpl.save(DatastoreImpl.java:656)
 at com.whaleal.mars.session.Datastore.save(Datastore.java:311)
 at com.whaleal.ops.web.api.service.impl.MongoDbDataServiceImpl.updateClusterInfo(MongoDbDataServiceImpl.java:1277)
 at com.whaleal.ops.web.api.service.impl.MongoDbDataServiceImpl$$FastClassBySpringCGLIB$$fe8dc17d.invoke(<generated>)
 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
 at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
 at com.whaleal.ops.web.api.config.PerformanceAspect.servicePerformance(PerformanceAspect.java:61)
 at sun.reflect.NativeMethodAccessorImp
```

**Comment by HbnKing** [comment]
主要原因为  getter  或者 setter  方法 调用时异常

**Comment by HbnKing** [comment]
请确保实体调用正常
